# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/user/Desktop/clion-1.0.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/user/Desktop/clion-1.0.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Dropbox/DIploma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Dropbox/DIploma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/user/Desktop/clion-1.0.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/user/Desktop/clion-1.0.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Dropbox/DIploma/CMakeFiles /home/user/Dropbox/DIploma/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Dropbox/DIploma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DIploma

# Build rule for target.
DIploma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DIploma
.PHONY : DIploma

# fast build rule for target.
DIploma/fast:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/build
.PHONY : DIploma/fast

gradient.o: gradient.cpp.o
.PHONY : gradient.o

# target to build an object file
gradient.cpp.o:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/gradient.cpp.o
.PHONY : gradient.cpp.o

gradient.i: gradient.cpp.i
.PHONY : gradient.i

# target to preprocess a source file
gradient.cpp.i:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/gradient.cpp.i
.PHONY : gradient.cpp.i

gradient.s: gradient.cpp.s
.PHONY : gradient.s

# target to generate assembly for a file
gradient.cpp.s:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/gradient.cpp.s
.PHONY : gradient.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/main.cpp.s
.PHONY : main.cpp.s

mep.o: mep.cpp.o
.PHONY : mep.o

# target to build an object file
mep.cpp.o:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/mep.cpp.o
.PHONY : mep.cpp.o

mep.i: mep.cpp.i
.PHONY : mep.i

# target to preprocess a source file
mep.cpp.i:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/mep.cpp.i
.PHONY : mep.cpp.i

mep.s: mep.cpp.s
.PHONY : mep.s

# target to generate assembly for a file
mep.cpp.s:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/mep.cpp.s
.PHONY : mep.cpp.s

threaded.o: threaded.cpp.o
.PHONY : threaded.o

# target to build an object file
threaded.cpp.o:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/threaded.cpp.o
.PHONY : threaded.cpp.o

threaded.i: threaded.cpp.i
.PHONY : threaded.i

# target to preprocess a source file
threaded.cpp.i:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/threaded.cpp.i
.PHONY : threaded.cpp.i

threaded.s: threaded.cpp.s
.PHONY : threaded.s

# target to generate assembly for a file
threaded.cpp.s:
	$(MAKE) -f CMakeFiles/DIploma.dir/build.make CMakeFiles/DIploma.dir/threaded.cpp.s
.PHONY : threaded.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DIploma"
	@echo "... gradient.o"
	@echo "... gradient.i"
	@echo "... gradient.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mep.o"
	@echo "... mep.i"
	@echo "... mep.s"
	@echo "... threaded.o"
	@echo "... threaded.i"
	@echo "... threaded.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

